POST http://localhost:3333/events
Content-Type: 'application/json'

{
  "title": "Novo Evento Unite",
  "details" : null,
  "maximumAttendees": 120
}

###

POST http://localhost:3333/events/70da7987-bad6-4217-8abf-5c36dca07863/attendee
Content-Type: 'application/json'

{
  "name": "Deividi Coradi",
  "email" : "deividi@teste.com"
}

###
GET http://localhost:3333/events/05cb3e61-67d4-4e6a-8bc6-6f5b4d759bbb
###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/05cb3e61-67d4-4e6a-8bc6-6f5b4d759bbb/attendees
